// Questions
var q = [
	"What are you building",
	// "whats a biggest blocker right now",
	"whats the progress so far",
	"whats your background",
	"tell us a bit about your story",
	"whats the unique insight",
	"How will you get to a 1000 users",
	"Whats the key differentiator when it comes to competitors",
	"How are they solving the problem right now",
	"who does what in the team",
	"Why isn't jawad full-time?",
	"What stage is the product at right now",
	"Whats your traction so far/Is anyone using you",
	"Have you noticed any surprising user behavior, What have you learned from your customers",
	"How are your customers using you",
	"How are you acquiring customer",
	"Who is your customer",
	'What resistance will they have to trying you and how will you overcome it?',
	"Do you have any other ideas around growth and fundraising",
	"Who are your competitors? Who do you fear the most? What do you understand that others don\’t",
	"What's stopping 'competitor' from building you",
	'How big can this get',
	'7 years from now, what would the world look like if you were successful',
	"How will we get to 1billion dollars, growth",
	"Why is your product priced the way it is?",
	"How long can you go before funding?",
	"Are you raising money right now?",
	"who is going to be your next hire?",
	"What use-cases are they using your product for?",
	"How long have you been working on this?",
	"Why did you pick this idea to work on?",
	"Why are you applying to pear-x",
	"whats your goal, end of YC",
	"how many people are on your team",
	"who does what",
	'So what the hell are you working on!!!!?',
	'How did you validate this',
	'Who are the users',
	'What KPIs are you focusing on? What metric are you trying to move? What are you trying to optimize for?',
	'What do the numbers look like right now?',
	'What domain expertise do you have?',
	'Whats the state of your product?',
	"Who uses your product? Or Who will use your product?",
	'what are the key drivers to your business? Why do people use you right now? What drives them to use your product?',
	"who are your competitors? Why would people use you over them?",
	"whats your revenue? How much are you earning from your users?",
	"When will you generate revenue?",
	"How many companies are you talking to every week? How are you finding them?",
	"Why are you applying to ERA?",
	"Where will the company be based?",
	"What is the expected valuation of the company at the end of the program?",
	"How long have you been working on this? How many of it has been full-time?",
	'What use-cases are they using your product for?',
	'How many customers do you need to be breakeven?',
	'How much do you charge customers? Whats your pricing model?',
	'What are you going to do during the ERA program',
	'how do you plan to use the funds? where will you spend the money?',
	'who does what?',
	'how did you guys meet?',
	'whats each of your backgrounds?',
	'what projects have you guys worked on before this?',
	'whats your TAM?',
	'why the hell would people use this product?',
	"Why the hell would companies use your product as opposed to sagemaker, or mlflow?",
	"what problem does your product solve?",
	"How will you get to paying customers",
	"Why hasn't someone done this before?",
	'What do you understand that others don&#39;t?',
	'Why will you succeed?',
	'How big an opportunity is there?',
	'What problems/hurdles are you anticipating?',
	'How much does customer acquisition cost?',
	'How will you make money?',
	'How much money could you make per year?',
	'How many users do you have?',
	'What is your user growth rate?',
	'How many users are paying?',
	'How are you meeting customers?',
	'How are you understanding customer needs?',
	'How will you get users?',
	'Who would you hire or how would you add to your team?',
	'Do you have a demo?',
	'Where is the rocket science here?',
	'How does your product work in more detail?',
	'How is your product different?',
	'What are you going to do next?',
	'What&#39;s new about what you make?',
	'What, exactly, makes you different from existing options?',
	'Who needs what you&#39;re making?',
	'How do you know customers need what you&#39;re making?',
	'Why isn&#39;t someone already doing this?',
	'What obstacles will you face and how will you overcome them?',
	'How will customers and/or users find out about you?',
	'What resistance will they have to trying you and how will you overcome it?',
	'What are the key things about your field that outsiders don&#39;t understand?',
	'What part of your project are you going to build first?',
	'Who is going to be your first paying customer?',
	'If your startup succeeds, what additional areas might you be able to expand into?',
	'Why did you choose this idea?',
	'What have you learned so far from working on your product?',
	'Six months from now, what&#39;s going to be your biggest problem?',
	'Where do new users come from?',
	'What is your growth like?',
	// 'What&#39;s the conversion rate?',
	'What makes new users try you?',
	'Why do the reluctant users hold back?',
	'What are the top things users want?',
	'What has surprised you about user behaviour?',
	'What&#39;s an impressive thing you have done?',
	'What do you understand about your users?',
	'Why did you pick this idea to work on?',
	'What domain expertise do you have?',
	'Who are your competitors?',
	'Who might become competitors?',
	'Someone just showed us an idea like this right before you guys. I don&#39;t like it. What else do you have?',
	'What competition do you fear most?',
	'What is your distribution strategy?',
	'How did your team meet?',
	'Why did your team get together?',
	'Who in your team does what?',
	'Who is &quot;the boss&quot;?',
	'What will you do if we don&#39;t fund you?',
	'Would you relocate to Silicon Valley?',
	'How do we know your team will stick together?',
	'What else have you created together?',
	'Are you open to changing your idea?',
	'What systems have you hacked?',
	'Tell us about a tough problem you solved?',
	'In what ways are you resourceful?',
	'Will you reincorporate as a US company?',
	'Will your team stick at this?',
	'Tell us something surprising you have done?',
	'What&#39;s the funniest thing that has happened to you?',
	'What&#39;s the worst thing that has happened?',
	'What&#39;s the biggest mistake you have made?',
	'What is your burn rate?',
	'How long can you go before funding?',
	'What is the next step with the product evolution?',
	'Have you raised funding?',
	'Who would be your next hire?',
	'How do you know people want this?',
	'What do you know about this space/product others don&#39;t know?'
];

// // Tips
var tips = [
	'Try to have quick and concise answers.',
	'Try to answer in 2 to 3 sentences.',
	'Answer like you would in a conversation, this is not a presentation.',
	'When talking to PG and the other YC partners, be substantive, and get straight to the point.',
	'DO NOT BEAT AROUND THE BUSH. Do not hem and haw. "Uhm"s and "uh"s don&#39;t lend an aura of intelligence.',
	'Use precise and concise language. You aren&#39;t pitching a VC that will ask you what your "secret sauce" is.',
	'He talks quickly, and so do the other YC partners. Try to match their tempo (as you should when talking to anyone).'
];